// Mocks generated by Mockito 5.4.4 from annotations
// in ecommers/test/helper/test_hlper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:convert' as _i25;
import 'dart:typed_data' as _i27;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ecommers/core/Error/failure.dart' as _i13;
import 'package:ecommers/core/network/check_connectivity.dart' as _i16;
import 'package:ecommers/features/ecommerce/Data/data_source/local_data_source.dart'
    as _i17;
import 'package:ecommers/features/ecommerce/Data/data_source/remote_data_source.dart'
    as _i15;
import 'package:ecommers/features/ecommerce/Data/model/ecommerce_model.dart'
    as _i4;
import 'package:ecommers/features/ecommerce/Domain/entity/ecommerce_entity.dart'
    as _i14;
import 'package:ecommers/features/ecommerce/Domain/repositories/ecommerce_repositories.dart'
    as _i7;
import 'package:ecommers/features/ecommerce/Domain/usecase/ecommerce_usecase.dart'
    as _i8;
import 'package:ecommers/features/ecommerce/presentation/state/image_input_display/image_bloc.dart'
    as _i21;
import 'package:ecommers/features/ecommerce/presentation/state/image_input_display/image_event.dart'
    as _i22;
import 'package:ecommers/features/ecommerce/presentation/state/image_input_display/image_state.dart'
    as _i10;
import 'package:ecommers/features/ecommerce/presentation/state/input_button_activation/bottum_state.dart'
    as _i11;
import 'package:ecommers/features/ecommerce/presentation/state/input_button_activation/button_bloc.dart'
    as _i23;
import 'package:ecommers/features/ecommerce/presentation/state/input_button_activation/button_event.dart'
    as _i24;
import 'package:ecommers/features/ecommerce/presentation/state/product_bloc/product_bloc.dart'
    as _i18;
import 'package:ecommers/features/ecommerce/presentation/state/product_bloc/product_event.dart'
    as _i19;
import 'package:ecommers/features/ecommerce/presentation/state/product_bloc/product_state.dart'
    as _i9;
import 'package:flutter_bloc/flutter_bloc.dart' as _i20;
import 'package:http/http.dart' as _i3;
import 'package:internet_connection_checker/internet_connection_checker.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i26;
import 'package:shared_preferences/shared_preferences.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeClient_1 extends _i1.SmartFake implements _i3.Client {
  _FakeClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEcommerceModel_2 extends _i1.SmartFake
    implements _i4.EcommerceModel {
  _FakeEcommerceModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternetConnectionChecker_3 extends _i1.SmartFake
    implements _i5.InternetConnectionChecker {
  _FakeInternetConnectionChecker_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_4 extends _i1.SmartFake implements Duration {
  _FakeDuration_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddressCheckResult_5 extends _i1.SmartFake
    implements _i5.AddressCheckResult {
  _FakeAddressCheckResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_6 extends _i1.SmartFake
    implements _i6.SharedPreferences {
  _FakeSharedPreferences_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEcommerceRepositories_7 extends _i1.SmartFake
    implements _i7.EcommerceRepositories {
  _FakeEcommerceRepositories_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEcommerceUsecase_8 extends _i1.SmartFake
    implements _i8.EcommerceUsecase {
  _FakeEcommerceUsecase_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductState_9 extends _i1.SmartFake implements _i9.ProductState {
  _FakeProductState_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeImageState_10 extends _i1.SmartFake implements _i10.ImageState {
  _FakeImageState_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBottumState_11 extends _i1.SmartFake implements _i11.BottumState {
  _FakeBottumState_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_12 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_13 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EcommerceRepositories].
///
/// See the documentation for Mockito's code generation for more information.
class MockEcommerceRepositories extends _i1.Mock
    implements _i7.EcommerceRepositories {
  MockEcommerceRepositories() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i2.Either<_i13.Failure, _i14.EcommerceEntity>> getProductById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductById,
          [id],
        ),
        returnValue:
            _i12.Future<_i2.Either<_i13.Failure, _i14.EcommerceEntity>>.value(
                _FakeEither_0<_i13.Failure, _i14.EcommerceEntity>(
          this,
          Invocation.method(
            #getProductById,
            [id],
          ),
        )),
      ) as _i12.Future<_i2.Either<_i13.Failure, _i14.EcommerceEntity>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, List<_i14.EcommerceEntity>>>
      getAllProduct() => (super.noSuchMethod(
            Invocation.method(
              #getAllProduct,
              [],
            ),
            returnValue: _i12.Future<
                    _i2.Either<_i13.Failure, List<_i14.EcommerceEntity>>>.value(
                _FakeEither_0<_i13.Failure, List<_i14.EcommerceEntity>>(
              this,
              Invocation.method(
                #getAllProduct,
                [],
              ),
            )),
          ) as _i12
              .Future<_i2.Either<_i13.Failure, List<_i14.EcommerceEntity>>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, bool>> addProduct(
          Map<String, dynamic>? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [product],
        ),
        returnValue: _i12.Future<_i2.Either<_i13.Failure, bool>>.value(
            _FakeEither_0<_i13.Failure, bool>(
          this,
          Invocation.method(
            #addProduct,
            [product],
          ),
        )),
      ) as _i12.Future<_i2.Either<_i13.Failure, bool>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, bool>> editeProduct(
    String? id,
    Map<String, dynamic>? product,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editeProduct,
          [
            id,
            product,
          ],
        ),
        returnValue: _i12.Future<_i2.Either<_i13.Failure, bool>>.value(
            _FakeEither_0<_i13.Failure, bool>(
          this,
          Invocation.method(
            #editeProduct,
            [
              id,
              product,
            ],
          ),
        )),
      ) as _i12.Future<_i2.Either<_i13.Failure, bool>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, bool>> deleteProduct(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i12.Future<_i2.Either<_i13.Failure, bool>>.value(
            _FakeEither_0<_i13.Failure, bool>(
          this,
          Invocation.method(
            #deleteProduct,
            [id],
          ),
        )),
      ) as _i12.Future<_i2.Either<_i13.Failure, bool>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, Map<String, dynamic>>> selectImage() =>
      (super.noSuchMethod(
        Invocation.method(
          #selectImage,
          [],
        ),
        returnValue:
            _i12.Future<_i2.Either<_i13.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i13.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #selectImage,
            [],
          ),
        )),
      ) as _i12.Future<_i2.Either<_i13.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [EcommerceRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockEcommerceRemoteDataSourceImpl extends _i1.Mock
    implements _i15.EcommerceRemoteDataSourceImpl {
  MockEcommerceRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.Client);

  @override
  _i12.Future<_i4.EcommerceModel> getProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [id],
        ),
        returnValue:
            _i12.Future<_i4.EcommerceModel>.value(_FakeEcommerceModel_2(
          this,
          Invocation.method(
            #getProduct,
            [id],
          ),
        )),
      ) as _i12.Future<_i4.EcommerceModel>);

  @override
  _i12.Future<List<_i4.EcommerceModel>> getAllProducts() => (super.noSuchMethod(
        Invocation.method(
          #getAllProducts,
          [],
        ),
        returnValue:
            _i12.Future<List<_i4.EcommerceModel>>.value(<_i4.EcommerceModel>[]),
      ) as _i12.Future<List<_i4.EcommerceModel>>);

  @override
  _i12.Future<bool> deleteProduct(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> editProduct(
    String? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProduct,
          [
            id,
            data,
          ],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> addProduct(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [data],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
}

/// A class which mocks [NetworkInfoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfoImpl extends _i1.Mock implements _i16.NetworkInfoImpl {
  MockNetworkInfoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.InternetConnectionChecker get connectionChecker => (super.noSuchMethod(
        Invocation.getter(#connectionChecker),
        returnValue: _FakeInternetConnectionChecker_3(
          this,
          Invocation.getter(#connectionChecker),
        ),
      ) as _i5.InternetConnectionChecker);

  @override
  _i12.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
}

/// A class which mocks [InternetConnectionChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnectionChecker extends _i1.Mock
    implements _i5.InternetConnectionChecker {
  MockInternetConnectionChecker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get checkInterval => (super.noSuchMethod(
        Invocation.getter(#checkInterval),
        returnValue: _FakeDuration_4(
          this,
          Invocation.getter(#checkInterval),
        ),
      ) as Duration);

  @override
  Duration get checkTimeout => (super.noSuchMethod(
        Invocation.getter(#checkTimeout),
        returnValue: _FakeDuration_4(
          this,
          Invocation.getter(#checkTimeout),
        ),
      ) as Duration);

  @override
  List<_i5.AddressCheckOptions> get addresses => (super.noSuchMethod(
        Invocation.getter(#addresses),
        returnValue: <_i5.AddressCheckOptions>[],
      ) as List<_i5.AddressCheckOptions>);

  @override
  set addresses(List<_i5.AddressCheckOptions>? value) => super.noSuchMethod(
        Invocation.setter(
          #addresses,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<bool> get hasConnection => (super.noSuchMethod(
        Invocation.getter(#hasConnection),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<_i5.InternetConnectionStatus> get connectionStatus =>
      (super.noSuchMethod(
        Invocation.getter(#connectionStatus),
        returnValue: _i12.Future<_i5.InternetConnectionStatus>.value(
            _i5.InternetConnectionStatus.connected),
      ) as _i12.Future<_i5.InternetConnectionStatus>);

  @override
  _i12.Stream<_i5.InternetConnectionStatus> get onStatusChange =>
      (super.noSuchMethod(
        Invocation.getter(#onStatusChange),
        returnValue: _i12.Stream<_i5.InternetConnectionStatus>.empty(),
      ) as _i12.Stream<_i5.InternetConnectionStatus>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  bool get isActivelyChecking => (super.noSuchMethod(
        Invocation.getter(#isActivelyChecking),
        returnValue: false,
      ) as bool);

  @override
  _i12.Future<_i5.AddressCheckResult> isHostReachable(
          _i5.AddressCheckOptions? options) =>
      (super.noSuchMethod(
        Invocation.method(
          #isHostReachable,
          [options],
        ),
        returnValue:
            _i12.Future<_i5.AddressCheckResult>.value(_FakeAddressCheckResult_5(
          this,
          Invocation.method(
            #isHostReachable,
            [options],
          ),
        )),
      ) as _i12.Future<_i5.AddressCheckResult>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i6.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i12.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);
}

/// A class which mocks [LocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSourceImpl extends _i1.Mock
    implements _i17.LocalDataSourceImpl {
  MockLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_6(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i6.SharedPreferences);

  @override
  _i12.Future<List<_i4.EcommerceModel>> getAllFromLocal() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFromLocal,
          [],
        ),
        returnValue:
            _i12.Future<List<_i4.EcommerceModel>>.value(<_i4.EcommerceModel>[]),
      ) as _i12.Future<List<_i4.EcommerceModel>>);

  @override
  _i12.Future<_i4.EcommerceModel> getSingleProduct(String? num) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSingleProduct,
          [num],
        ),
        returnValue:
            _i12.Future<_i4.EcommerceModel>.value(_FakeEcommerceModel_2(
          this,
          Invocation.method(
            #getSingleProduct,
            [num],
          ),
        )),
      ) as _i12.Future<_i4.EcommerceModel>);

  @override
  _i12.Future<bool> addCach(_i4.EcommerceModel? data) => (super.noSuchMethod(
        Invocation.method(
          #addCach,
          [data],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);

  @override
  _i12.Future<bool> deleteCach(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCach,
          [id],
        ),
        returnValue: _i12.Future<bool>.value(false),
      ) as _i12.Future<bool>);
}

/// A class which mocks [EcommerceUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockEcommerceUsecase extends _i1.Mock implements _i8.EcommerceUsecase {
  MockEcommerceUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.EcommerceRepositories get repositories => (super.noSuchMethod(
        Invocation.getter(#repositories),
        returnValue: _FakeEcommerceRepositories_7(
          this,
          Invocation.getter(#repositories),
        ),
      ) as _i7.EcommerceRepositories);

  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, List<_i14.EcommerceEntity>>>
      dataForAll() => (super.noSuchMethod(
            Invocation.method(
              #dataForAll,
              [],
            ),
            returnValue: _i12.Future<
                    _i2.Either<_i13.Failure, List<_i14.EcommerceEntity>>>.value(
                _FakeEither_0<_i13.Failure, List<_i14.EcommerceEntity>>(
              this,
              Invocation.method(
                #dataForAll,
                [],
              ),
            )),
          ) as _i12
              .Future<_i2.Either<_i13.Failure, List<_i14.EcommerceEntity>>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, _i14.EcommerceEntity>> dataById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #dataById,
          [id],
        ),
        returnValue:
            _i12.Future<_i2.Either<_i13.Failure, _i14.EcommerceEntity>>.value(
                _FakeEither_0<_i13.Failure, _i14.EcommerceEntity>(
          this,
          Invocation.method(
            #dataById,
            [id],
          ),
        )),
      ) as _i12.Future<_i2.Either<_i13.Failure, _i14.EcommerceEntity>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, bool>> editProduct(
    String? id,
    Map<String, dynamic>? jsonString,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editProduct,
          [
            id,
            jsonString,
          ],
        ),
        returnValue: _i12.Future<_i2.Either<_i13.Failure, bool>>.value(
            _FakeEither_0<_i13.Failure, bool>(
          this,
          Invocation.method(
            #editProduct,
            [
              id,
              jsonString,
            ],
          ),
        )),
      ) as _i12.Future<_i2.Either<_i13.Failure, bool>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, bool>> deleteProduct(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i12.Future<_i2.Either<_i13.Failure, bool>>.value(
            _FakeEither_0<_i13.Failure, bool>(
          this,
          Invocation.method(
            #deleteProduct,
            [id],
          ),
        )),
      ) as _i12.Future<_i2.Either<_i13.Failure, bool>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, bool>> addProducts(
          Map<String, dynamic>? jsonString) =>
      (super.noSuchMethod(
        Invocation.method(
          #addProducts,
          [jsonString],
        ),
        returnValue: _i12.Future<_i2.Either<_i13.Failure, bool>>.value(
            _FakeEither_0<_i13.Failure, bool>(
          this,
          Invocation.method(
            #addProducts,
            [jsonString],
          ),
        )),
      ) as _i12.Future<_i2.Either<_i13.Failure, bool>>);

  @override
  _i12.Future<_i2.Either<_i13.Failure, Map<String, dynamic>>> selectImage() =>
      (super.noSuchMethod(
        Invocation.method(
          #selectImage,
          [],
        ),
        returnValue:
            _i12.Future<_i2.Either<_i13.Failure, Map<String, dynamic>>>.value(
                _FakeEither_0<_i13.Failure, Map<String, dynamic>>(
          this,
          Invocation.method(
            #selectImage,
            [],
          ),
        )),
      ) as _i12.Future<_i2.Either<_i13.Failure, Map<String, dynamic>>>);
}

/// A class which mocks [ProductBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductBloc extends _i1.Mock implements _i18.ProductBloc {
  MockProductBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.EcommerceUsecase get ecommerceUsecase => (super.noSuchMethod(
        Invocation.getter(#ecommerceUsecase),
        returnValue: _FakeEcommerceUsecase_8(
          this,
          Invocation.getter(#ecommerceUsecase),
        ),
      ) as _i8.EcommerceUsecase);

  @override
  _i9.ProductState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeProductState_9(
          this,
          Invocation.getter(#state),
        ),
      ) as _i9.ProductState);

  @override
  _i12.Stream<_i9.ProductState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<_i9.ProductState>.empty(),
      ) as _i12.Stream<_i9.ProductState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i19.ProductEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i19.ProductEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i9.ProductState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i19.ProductEvent>(
    _i20.EventHandler<E, _i9.ProductState>? handler, {
    _i20.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i20.Transition<_i19.ProductEvent, _i9.ProductState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void onChange(_i20.Change<_i9.ProductState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ImageBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageBloc extends _i1.Mock implements _i21.ImageBloc {
  MockImageBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.EcommerceUsecase get ecommerceUsecase => (super.noSuchMethod(
        Invocation.getter(#ecommerceUsecase),
        returnValue: _FakeEcommerceUsecase_8(
          this,
          Invocation.getter(#ecommerceUsecase),
        ),
      ) as _i8.EcommerceUsecase);

  @override
  _i10.ImageState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeImageState_10(
          this,
          Invocation.getter(#state),
        ),
      ) as _i10.ImageState);

  @override
  _i12.Stream<_i10.ImageState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<_i10.ImageState>.empty(),
      ) as _i12.Stream<_i10.ImageState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i22.ImageEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i22.ImageEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i10.ImageState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i22.ImageEvent>(
    _i20.EventHandler<E, _i10.ImageState>? handler, {
    _i20.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i20.Transition<_i22.ImageEvent, _i10.ImageState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void onChange(_i20.Change<_i10.ImageState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ButtonBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockButtonBloc extends _i1.Mock implements _i23.ButtonBloc {
  MockButtonBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.EcommerceUsecase get ecommerceUsecase => (super.noSuchMethod(
        Invocation.getter(#ecommerceUsecase),
        returnValue: _FakeEcommerceUsecase_8(
          this,
          Invocation.getter(#ecommerceUsecase),
        ),
      ) as _i8.EcommerceUsecase);

  @override
  _i11.BottumState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeBottumState_11(
          this,
          Invocation.getter(#state),
        ),
      ) as _i11.BottumState);

  @override
  _i12.Stream<_i11.BottumState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i12.Stream<_i11.BottumState>.empty(),
      ) as _i12.Stream<_i11.BottumState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  void add(_i24.ButtonEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i24.ButtonEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i11.BottumState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i24.ButtonEvent>(
    _i20.EventHandler<E, _i11.BottumState>? handler, {
    _i20.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i20.Transition<_i24.ButtonEvent, _i11.BottumState>? transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i12.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i12.Future<void>.value(),
        returnValueForMissingStub: _i12.Future<void>.value(),
      ) as _i12.Future<void>);

  @override
  void onChange(_i20.Change<_i11.BottumState>? change) => super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i3.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i3.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<_i3.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<String>.value(_i26.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<_i27.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<_i27.Uint8List>.value(_i27.Uint8List(0)),
      ) as _i12.Future<_i27.Uint8List>);

  @override
  _i12.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i12.Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_13(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i12.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i3.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i3.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<_i3.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i12.Future<_i3.Response>.value(_FakeResponse_12(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i12.Future<_i3.Response>);

  @override
  _i12.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<String>.value(_i26.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i12.Future<String>);

  @override
  _i12.Future<_i27.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i12.Future<_i27.Uint8List>.value(_i27.Uint8List(0)),
      ) as _i12.Future<_i27.Uint8List>);

  @override
  _i12.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i12.Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_13(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i12.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
